### ISSUE TITLE
Provide working download links for Widnows portable archives on the website

### ISSUE THREAD

**Issue by Globe51** [jellyfin/jellyfin.org#1025]
https://jellyfin.org/docs/general/installation/windows/#install-manually-portable suggests that to update the portable version of Jellyfin, one has to 'download the latest version', but there is no link to where one should look for this version.

There is a portable zip file linked to on the downloads page accessable from here https://jellyfin.org/downloads/server, but the zip file contains no executable.

By following a link on this page https://www.reddit.com/r/jellyfin/comments/z2nqqj/windows_portable/ I was able to locate a "combined"? version of Jellyfin 10.8.3, but the client app is saying that I will need to have my server updated to 10.9.0 or later. I cannot find a "combined" archive for this version.

**Comment by felix920506** [comment]
They are already provided.

**Comment by thornbill** [comment]
Try https://repo.jellyfin.org/?path=/server/windows

You do not want the "dotnet portable" version.
