### ISSUE TITLE
NEWBIE

### ISSUE THREAD

**Issue by 1Goldhdtv** [jellyfin/jellyfin.org#1106]
I AM NOT SURE IF I AM IN THE CORRECT FORUM BUT I.LL GIVE IT A SHOT. I NEED SOMEONE TO HELP WITH ALL THE INITIAL CONTENT  SET UP. I NEED ALL MY CONTENT MIGRATED/SWITCHED TO JELLYFIN. LITERALLY EVERYTHING FROM START TO FINISH. I HAVE SEEN MY SAME CONTENT BEING USE WITH JELLYFIN INTERFACE AND IT IS AWESOME. ANY HELP OR POINT ME IN THE RIGHT DIRECTION WOULD BE GREAT!!!

**Comment by felix920506** [comment]
Please head to our forum or chat rooms for troubleshooting help. https://jellyfin.org.contact

**Comment by 1Goldhdtv** [comment]
Thanks felix920506


Sent from Yahoo Mail for iPhone


On Monday, September 9, 2024, 1:28 PM, felix920506 ***@***.***> wrote:




Please head to our forum or chat rooms for troubleshooting help. https://jellyfin.org.contact
