### ISSUE TITLE
Reference links are broken in codec documentation

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin.org#120]
http://next.jellyfin.org/docs/general/clients/codec-support

**Comment by leewan-09** [comment]
Are you referring to these? 

<img width="817" alt="image" src="https://user-images.githubusercontent.com/60838584/189223340-c4b6fb83-86a9-4263-a6d1-bd0a07e0577e.png">

If that is the case, I believe that issue is caused by because `<sup></sup>` tag.

**Comment by thornbill** [comment]
Yes those are the ones I had noticed.
