### ISSUE TITLE
Matrix Channel list broken

### ISSUE THREAD

**Issue by MinecraftPlaye** [jellyfin/jellyfin.org#170]
Scrolling through the [Jellyfin Next site](https://next.jellyfin.org/docs/general/getting-help), the matrix channel list seems not to properly load:

![image](https://user-images.githubusercontent.com/9168045/190705826-f45d1785-f3fa-4fb4-9e35-c89121b7b906.png)
That seems to be an issue on the main site as well.

Tested with Firefox 104 without being logged in to any matrix client.

**Comment by MinecraftPlaye** [comment]
> I've noticed this one also... sometimes half the list will show up correctly for me and the rest won't, sometimes none of them will, but maybe it's best to just remove the badges for these.

If fixing it is not possible or worth the hassle, then removing them is definitely less confusing to the user than having badges that tell you the server is inaccessible.

**Comment by nielsvanvelzen** [comment]
It might make sense to just like to the contact page where we have all rooms linked to matrix.to, which shows the actual user count.

**Comment by thornbill** [comment]
Good point @nielsvanvelzen. I had noticed there is a decent amount of duplicate content between the main site and docs (probably because they have been pretty disjointed in the past). I think linking to the main Contact page is the best solution here.
