### ISSUE TITLE
Comics / Mangas documentation broken on next.jellyfin.org

### ISSUE THREAD

**Issue by MinecraftPlaye** [jellyfin/jellyfin.org#171]
How it looks on [next.jellyfin.org](http://next.jellyfin.org/docs/general/server/media/comics):
![image](https://user-images.githubusercontent.com/9168045/190706564-86e060f7-1fb1-4cb0-8624-37868efe2fab.png)

How it should look (and how it does look on [Jellyfin.org](https://jellyfin.org/docs/general/server/media/comics) ):
![image](https://user-images.githubusercontent.com/9168045/190706645-96df59c0-cfe1-415e-aa63-d83536f55bdd.png)

Tested with firefox 104 on Fedora 36.

**Comment by alanazar** [comment]
This issue has been fixed and can now be closed
