### ISSUE TITLE
Incorrect GPG key URIs in manual installation instructions for Debian and Ubuntu distros

### ISSUE THREAD

**Issue by ralgar** [jellyfin/jellyfin.org#367]
## Problems

1. The URIs for the Jellyfin GPG key in the manual [Debian](https://jellyfin.org/docs/general/installation/linux#debian) / [Ubuntu](https://jellyfin.org/docs/general/installation/linux/#ubuntu-repository) installation instructions have been outdated since they were [changed 2 years ago](https://jellyfin.org/posts/jellyfin-apt-key/). As a result, these instructions are fundamentally broken for users that don't have the experience to troubleshoot the issue on their own.
2. In the same sections / code blocks, the preceding `mkdir` command also errors out on systems where `/etc/apt/keyrings` already exists. This isn't a critical issue, but it could confuse inexperienced users to see the error message, particularly when pasting and running the entire code block in one shot.

## Solutions

I'll be opening a PR, in a few moments, with the following changes:

1. Update all URIs in the documentation pointing to the Jellyfin GPG key (there were only two).
1. Update the `mkdir` commands to `mkdir -p`, so they don't error out when the directory already exists.

**Comment by joshuaboniface** [comment]
Great find. I recall making that additional symlink but guess I forgot to update the docs.

**Comment by ralgar** [comment]
Was brought to my attention by a user in r/jellyfin who was having issues. Thanks for getting it merged so quickly! :heart:
