### ISSUE TITLE
SQLite3 queries to unlock users doesn't work

### ISSUE THREAD

**Issue by mathsyx69** [jellyfin/jellyfin.org#425]
Hello,

I was trying to make a bash script to reinitialize failed login attempt counter and unlock a user from jellyfin but I realized that the given queries in documentation do not work : 

https://jellyfin.org/docs/general/administration/troubleshooting/#linux-cli

Can you fix that in the documentation ?

Thank in advance,

M.A

**Comment by sakej** [comment]
What exactly does not work for you?

I've just checked those and they work just fine, so either your script does not have permission to change the file,
or you do not change 'LockedUserName' for an actual username of a user.

**Comment by mathsyx-fr** [comment]
Thank for response.

When I execute the commands, the user isn't unlock, and for the failed login count I'm not sure it's reset. How I can't verify it's work ?
