### ISSUE TITLE
jellyfin-web Unstable on jellyfin.org is months old

### ISSUE THREAD

**Issue by alexi741** [jellyfin/jellyfin.org#478]
Same as https://github.com/jellyfin/jellyfin-web/issues/4449.
I'm not sure if the bug belongs with jellyfin.org or jellyfin-web

## Describe The Bug ##
Unstable versions of jellyfin-web are not being updated on Jellyfin.org.

Current unstable: **20230315.12**
On Jellyfin.org: **20220906.1**

## Steps To Reproduce ##
https://repo.jellyfin.org/releases/server/debian/versions/unstable/web/
https://repo.jellyfin.org/releases/server/debian/unstable/
https://repo.jellyfin.org/releases/server/linux/unstable/web/

## Expected Behavior ##
The website will update to the current version of unstable

**Comment by nielsvanvelzen** [comment]
This repository is for the main website at jellyfin.org, not for repo.jellyfin.org.

**Comment by alexi741** [comment]
Where can I report issues about repo.jellyfin.org? [jellyfin-meta](https://github.com/jellyfin/jellyfin-meta/)?
