### ISSUE TITLE
Searching for title works but the title wont show otherwise

### ISSUE THREAD

**Issue by dconlrn** [jellyfin/jellyfin.org#609]
I have all the file permissions properly set and when I search for my movies they show up but jellyfin only says I have 476 when I have closer to 600. The movies above the 476 number do not show up when I browse through my library but when I search for them I find them. I cant remember all of the movies I have in my library otherwise it wouldnt be a problem

**Comment by thornbill** [comment]
This repository is for the Jellyfin.org website. Not for any issues you may have with the server or clients. Please see https://jellyfin.org/docs/general/getting-help
