### ISSUE TITLE
Arch Linux install instructions are out-of-date

### ISSUE THREAD

**Issue by enter-a-random-username** [jellyfin/jellyfin.org#678]
Arch Linux moved jellyfin-(server,web) from AUR to `Extra` package repo. :tada: 

https://archlinux.org/packages/extra/x86_64/jellyfin-server/
https://archlinux.org/packages/extra/x86_64/jellyfin-web/

```bash
pacman -S jellyfin-server jellyfin-web
```

**Comment by nielsvanvelzen** [comment]
#675
