### ISSUE TITLE
Installation instructions for Unraid

### ISSUE THREAD

**Issue by emillassen** [jellyfin/jellyfin.org#683]
The installation instructions provided [here](https://github.com/jellyfin/jellyfin.org/blob/master/docs/general/installation/container.md#unraid-docker), are not correct, as the official docker Jellyfin repo is not listed in the Community Apps (CA) plugin.

I believe that the template which is supposed to be available in the CA, is [this](https://github.com/jellyfin/jellyfin/tree/master/deployment/unraid/docker-templates), however it is also incorrect, as 'Template Repositories' have been [removed](https://forums.unraid.net/topic/112170-allow-template-repositories-to-be-hosted-from-other-sources/#comment-1126265) from Unraid.

I see two ways to remediate this problem.
1. Adding Jellyfin to CA following this [guide](https://forums.unraid.net/topic/57181-docker-faq/?do=findComment&comment=566084)
2. Adding detailed instructions for how to manually add the Jellyfin container in Unraid

Personally, I believe that it would be easiest for the end user if Jellyfin was listed in the CA. 
Do note that there are multiple docker images containing Jellyfin in the CA (binhex, linuxserver and hotio), but none use the official image.

**Comment by felix920506** [comment]
The official Unraid instructions have been removed in #697
Please open an issue on the main repo (https://github.com/jellyfin/jellyfin) if you believe there are errors with the contents over there.
