### ISSUE TITLE
Networking and Chromecast

### ISSUE THREAD

**Issue by jameskimmel** [jellyfin/jellyfin.org#714]
docs/general/networking/index.md
we have this warning:

```
In order for Chromecast to work on a non-public routable connection, 8.8.8.8 must be blocked on the Chromecast's Gateway. Blocking 8.8.8.8 on your router is the easiest solution to this problem.
```

I would argue that blocking alone is not sufficient.
You could block Google DNS and add an unbound override rule, so your local DNS points to your internal Jellyfin LAN IPv4.
You could also use NAT Reflection instead.
I would replace the warning with this:
```
In order for Chromecast to work on your local LAN, the easiest solution is to use IPv6 instead of IPv4. For IPv6 there is no differentiation between public and local IP. An IPv6 address can simultaneously be publicly routable and accessible from the local LAN.
For non-public routable IPv4 connections, you need to use NAT reflection to redirect to your local LAN IPv4. Another option would be to block Chromecast from reaching the Google DNS servers and add some unbound override rules to point to your local LAN IPv4
```
Just a rough draft to start a discussion. Would like to hear your thoughts.

**Comment by masterflitzer** [comment]
i like it, but one minor point that i'd not write like that: 

> For IPv6 there is no differentiation between public and local IP

not really correct, ipv6 has non publicly routable addresses like ula & link-local

**Comment by felix920506** [comment]
Please keep the issue open until the PR is merged.
