### ISSUE TITLE
Route metadata downloads through proxy

### ISSUE THREAD

**Issue by hizani** [jellyfin/jellyfin.org#737]
Hi!

I am currently unable to download any metadata from TMDB as the website banned all users from my country.

Is there a way to route metadata downloads through proxy to bypass this problem? If not, it would be great to see this feature in the future

**Comment by Shadowghost** [comment]
Please use the forum or our other support channels for this kind of questions.
Feature requests should be filed on out [Fider instance](https://features.jellyfin.org/).
