### ISSUE TITLE
Demo site is not clear with log-in credentials.

### ISSUE THREAD

**Issue by maru801** [jellyfin/jellyfin.org#874]
I've noticed the test/demo site on the website's main page (https://demo.jellyfin.org/stable), that you get to by clicking on the "See it in Action" button, doesn't make it clear that the user is supposed to log-in with "demo" as user, and no password.

There should be a clear indication of what a new user is supposed to do to log-in to the demo site somewhere near each button that takes the user to the demo site, or on the demo site's log-in page itself.

**Comment by thornbill** [comment]
![image](https://github.com/jellyfin/jellyfin.org/assets/3450688/fe6f3260-7d21-4554-a81e-07e604586e52)

Seems pretty clear to me. You probably just have a browser extension that is removing the disclaimer.

**Comment by maru801** [comment]
Yeah, spoke to soon. Just found out that my main browser blocks that specific message.
