### ISSUE TITLE
Update docs content

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin.org#89]
The docs site content needs ported over again since it is ~1 year out of date. There are also some pages that were in docs that were moved to the site root that should probably be moved back for now. 

The docs here were updated as of https://github.com/jellyfin/jellyfin-docs/commit/612a09258fe1793a091ce5d5cc365c0651a0c4f9.

The following changes need ported here to be current:

- [x] https://github.com/jellyfin/jellyfin-docs/pull/698
  - Blocked by https://github.com/jellyfin/jellyfin.org/pull/150
  - https://github.com/jellyfin/jellyfin.org/pull/217
- [x] https://github.com/jellyfin/jellyfin-docs/pull/705
  - https://github.com/jellyfin/jellyfin.org/pull/182
- [x] https://github.com/jellyfin/jellyfin-docs/pull/700
  - https://github.com/jellyfin/jellyfin.org/pull/182
- [x] https://github.com/jellyfin/jellyfin-docs/pull/708
  - https://github.com/jellyfin/jellyfin.org/pull/166
- [x] https://github.com/jellyfin/jellyfin-docs/pull/710
  - https://github.com/jellyfin/jellyfin.org/pull/217
- [x] https://github.com/jellyfin/jellyfin-docs/pull/712
  - https://github.com/jellyfin/jellyfin.org/pull/217
- [x] https://github.com/jellyfin/jellyfin-docs/pull/714
  - https://github.com/jellyfin/jellyfin.org/pull/217

**Comment by joshuaboniface** [comment]
Did the About page in #214

**Comment by thornbill** [comment]
This is being tracked under #218 now
